apiVersion: apps/v1
kind: Service
metadata: 
  name: my-service
spec:
  type: clusterIp
  selector:
    apps: myapp
  ports:
  -  protocol: tcp
     targetPort: 80
     port: 80
  -  protocol: tcp
     targetPort: 443
     port: 443
  -  protocol: ssh
     targetPort: 22
     port: 22


  
